version: '3.9'

services:
  backend:
    container_name: backend2.3
    build: ./backend
    ports:
      - 8080:8080
  frontend:
    container_name: frontend2.3
    build: ./frontend
    ports:
      - 5001:5001