version: '3.9'

services:
  backend:
    container_name: backend2.3
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - redis-cache
      - postgres
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DATABASE: mydatabase
  frontend:
    container_name: frontend2.3
    build: ./frontend
    ports:
      - 5001:5000
  redis-cache:
    container_name: redis-cache
    image: redis
    restart: unless-stopped
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    restart: unless-stopped
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

